[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/generate-pptx"
  status = 200
  force = true
